version: "3.8"

services:
  navigation-manager:
    image: uav-nav-image
    container_name: uab-nav-container
    restart: always
    build:
      context: ./
      dockerfile: ./uav-nav/Dockerfile
    #devices:
    #  - /dev/ttyAMA0 # pixhawk
    #  - /dev/video0